{% set version = "0.9.0" %}

package:
  name: glueviz
  version: {{version}}

source:
  fn: glueviz-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-{{version}}.tar.gz
  md5: 34b4923e4e2441a95b1830ede26ddca2

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  osx_is_app: True

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - astropy
    - ipython
    - ipykernel
    - h5py
    - pandas

    # The conda-forge version of PyQt 4.11.4 is currently broken because
    # it doesn't include session-related functionality, so we disallow
    # this version for now.
    - pyqt !=4.11.4

    - qtconsole
    - xlrd
    - scikit-image
    - python.app  # [osx]
    - setuptools
    - dill
    - plotly
    - qtpy

test:
  requires:
    - mock
    - pytest
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
