# NOTE: this is a meta-package that includes the core glue-core code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package. Even though glueviz is a
# Python package on PyPI, and has a setup.py file, we don't include a build command
# below since the only purpose of that command is to trigger the installation of the
# dependencies.
{% set version = "1.4.0" %}

package:
  name: glueviz
  version: {{version}}

build:
  number: 0
  # Skipping unnecessary linux platforms that don't need viz.
  skip: true  # [py<37 or ppc64le or s390x]

requirements:
  host:
    - python
  run:
    - glue-core =={{version}}
    - glue-vispy-viewers >=1.0.3

test:
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: https://glueviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_url: https://github.com/glue-viz/glueviz/blob/master/LICENSE
  dev_url: https://github.com/glue-viz/glueviz
  doc_url: http://docs.glueviz.org/
  summary: Multi-dimensional linked data exploration
  description: |
    This package does not contain any code, but instead
    is a meta-package that depends on the core glue code as well as stable
    plugins that we want to provide to users by default.  This installs
    glue-core and glue-vispy-viewers.


extra:
  recipe-maintainers:
    - astrofrog-conda-forge
