{% set version = "0.8.0" %}

package:
  name: glueviz
  version: {{version}}

source:
  fn: glueviz-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-{{version}}.tar.gz
  md5: 8cdb3db5001311cf77cbd4071ef9ac66

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  osx_is_app: True

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - astropy
    - ipython
    - ipykernel
    - h5py
    - pandas
    - pyqt
    - qtconsole
    - xlrd
    - scikit-image
    - python.app  # [osx]

test:
  requires:
    - mock
    - pytest
  imports:
    - glue
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
