{% set version = "0.8.1" %}

package:
  name: glueviz
  version: {{version}}

source:
  fn: glueviz-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-{{version}}.tar.gz
  md5: a14b261b391643c0c34253bd8281fa12

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  osx_is_app: True

requirements:

  build:
    - python
    - vs2015_runtime 14.00.23026.0 0  # [win and py35]

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - astropy
    - ipython
    - ipykernel
    - h5py
    - pandas
    - pyqt
    - qtconsole
    - xlrd
    - scikit-image
    - python.app  # [osx]
    - vs2015_runtime 14.00.23026.0 0  # [win and py35]

test:
  requires:
    - mock
    - pytest
  imports:
    - glue
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
