travis:
  secure:
    BINSTAR_TOKEN: Z41kRsAFB5jxqG98h5vaTa3Wzx4MhDQocx9S+F7CuB6gOTS4rfEcIKQMUSSSNP0/Mp6qrOnXab8aq51KWhVLvd1vXypjRSeqQJ2KYQeawXhRwCv4V4vKkpCvI5GRM7FBoihvlu5/CCr+l2m3wl/ZOpDerljNFyHgWOuTKb/4Q0/7e/oyZD1W3yKEzua/jELk0/dMfN4arEW/AL631qkBbJSPQgaYWXNyHQjf6oVm/gBXHt2Srds4BIvyQ53Is6oYJ1igkEAfCoH9ZqqUr8KXDWaFxQtSOHLy5eY4w4zLvcaEZ1u5tnIrFtjRouxd/2JKGrhb5qN2NYDD6F97j0G93MvB2bB2VVS9a/xCbTi1MrD9yCWKPRo6UYawPFgOFYl+uxvAlvZ61GDLaiMiwJAiLz2cSf72171yhWEFBhrkeHErVqHkfySDyWQyd8RM3iBeNWWck/R9zaDJlvmUMSWmklLSRKl6Z29L9kWVr9/+H2RbbHCBwcGVTxsKEqpZRgXpUPHWc1L1Qawmk+rCos+7+2TLE32/Su8gsCEmXzigtlTn4yEH6+CdhD3YCZ2dwywW7fBtWbohtQ7AIefp82tzjM62ihRFjWg3ua1udOcD+mBjgreOMcZOZn+ytdHKkTLd+KPa4RhmwI0yk6wVQj1HpwKiXgIEvvLKHUN5/BPIiLc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
max_r_ver: '35'
provider:
  win: azure
