travis:
  secure:
    BINSTAR_TOKEN: VMYSVl8MLK5lIZOtmV1xGodqFlrRK2gM2K8UKAWCUn21192ZVwv8R8ZZxUNLAXi5AD0YtPfMwblkIihu51M9xzy5m3TXO3BjS/FDrfv9rl7zO2KMTKKaABEjIjXGcQVpXUAygUypCauQh5xPLO3W5nomj/F5cT5zIIf0u3Et/WAvByolmbYeQaIonjew9QvhsSW69v0mXnW543sNs8YOUzIZvc00kP9WpCTTQ9lvusZFD/3+jnmeZjm8lK8wtey2MMcmflufH9ca/C64PY46TnyMrpPI8P2kB+TtJjhNCKSoyxh7oaDJ28fx0wU4mMfJECgUoiQWMUaG8E04+1Vy391saoQHyln2VPOsJRWHqojePjycfUkI9Q1g3EwMd9eKfNdj3JopZFXuzf5FsZN8oj0C0PddTW/oDKuj7ffruKz8xHaImqhSxa/jbirkaiTOGV6fiD4PC7tn+eCJsrjhkjL76ZwTrHCUYOgsw7F+dLZXlmypWlPwrcbykwLuy6AKN2elPv1px8kQjTZh97iy2yjOKWNnv3C8ZGYGkaJ3ZpVuN3HK3uGQcta18wWyy+q+GFSCkAvnUhwjK1XrQnTBCPfcj0eqAprojveW4wB24YZP9X/LUq/TPzv/IhNEt4slicn5/UhOXPtq1/BLoKVi2q32xhE+z3sCtsnAnDfCnqY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
